import type { Metadata } from "next";
import { ThemeProvider } from "./components/darkmode/theme-provider";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { store } from "./components/reduxtoolkit/store";
import Providers from "./components/reduxtoolkit/Providers";
import CornerStats from "@/components/ui/corner-stats";
import ServerStatus from "./components/ServerStatus"; // or ServerStatusBar

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Providers>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {/* Add Server Status Component */}
            <ServerStatus />
            {/* Or use ServerStatusBar for persistent notification bar */}
            {/* <ServerStatusBar /> */}
            
            {children}
            <CornerStats />
            <Toaster />
          </ThemeProvider>
        </Providers>
      </body>
    </html>
  );
}